app/main/__init__.py
# -*- coding: utf-8 -*-
"""
主蓝图初始化
"""

from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
# -*- coding: utf-8 -*-
"""
应用主视图
"""

import os
from uuid import uuid1
from datetime import datetime

from flask import abort, flash, redirect, render_template, request, url_for, current_app
from flask_login import current_user, login_required

from ..decorators import student_required, teacher_required
from ..extensions import db
from ..models import Class, Problem, Subject, Tag, User, UserType
from ..utils import allowed_file
from . import main


@main.route('/')
def index():
    """应用首页"""
    return render_template('main/index.html')


@main.route('/problems/')
@login_required
@student_required
def problems():
    """查看当前用户的所有错题"""
    # 获取所有错题
    all_problems = current_user.problems.order_by(Problem.timestamp.desc()).all()
    return render_template('main/problems.html', problems=all_problems)


@main.route('/problems/<int:id>/')
@login_required
@student_required
def problem(id):
    """查看当前用户的指定错题"""
    # 获取错题
    problem = current_user.problems.filter_by(id=id).first()
    if problem is None:
        abort(404)
    return render_template('main/problem.html', problem=problem)


@main.route('/problems/add/', methods=['GET', 'POST'])
@login_required
@student_required
def add_problem():
    """添加错题"""
    if request.method == 'POST':
        body = request.form.get('body-text')
        original_answer = request.form.get('original-answer-text')
        correct_answer = request.form.get('correct-answer-text')
        description = request.form.get('description-text')
        subject = request.form.get('subject')
        title = request.form.get('title')
        date = request.form.get('date')
        date = str(date).split('/')
        date = datetime(int(date[0]), int(date[1]), int(date[2]))
        tags = str(request.form.get('tags')).split('，')
        subject = Subject.query.get(int(subject))
        things = ['body', 'original-answer', 'correct-answer', 'description']
        is_image = [False, False, False, False]
        text = [body, original_answer, correct_answer, description]
        i = 0
        for thing in things:
            if request.form.get('%s-is-image' % thing) == 'True':
                photos = request.files.getlist('%s-image' % thing)
                for photo in photos:
                    if allowed_file(photo.filename):
                        filename = str(uuid1()) + '.' + \
                            photo.filename.rsplit('.', 1)[1]
                        photo.save(os.path.join(
                            current_app.config['UPLOADS_FOLDER'], filename))
                        is_image[i] = True
                        if text[i] is None:
                            text[i] = filename
                        else:
                            text[i] += (',' + filename)
                    else:
                        flash('请上传图片', 'warning')
                        return redirect(url_for('main.add_problem'))
            i += 1
        # 创建错题
        problem_ = Problem(body=text[0].replace('\r\n', '<br>'), original_answer=text[1].replace('\r\n', '<br>'),
                           correct_answer=text[2].replace('\r\n', '<br>'), description=text[3].replace('\r\n', '<br>'),
                           author=current_user, subject=subject, body_is_image=is_image[0],
                           original_answer_is_image=is_image[1], correct_answer_is_image=is_image[2],
                           description_is_image=is_image[3], title=title, timestamp=date)
        db.session.add(problem_)
        db.session.commit()
        # 添加没有的标签
        for tag in tags:
            if tag != '' and not current_user.tags.filter_by(name=tag).first():
                tag = Tag(name=tag, owner=current_user, subject=subject)
                db.session.add(tag)
            elif current_user.tags.filter_by(name=tag).first() and current_user.tags.filter_by(name=tag).first().subject != subject and (not current_user.tags.filter_by(subject=subject).first()):
                tag = Tag(name=tag, owner=current_user, subject=subject)
                db.session.add(tag)
            else:
                tags_ = Tag.query.filter_by(name=tag).all()
                for tag_ in tags_:
                    if tag_.subject == subject:
                        tag = tag_
                        break
            try:
                tag.add_problem(problem_)
            except AttributeError:
                tag = Tag(name=tag, owner=current_user, subject=subject)
                tag.add_problem(problem_)
        db.session.commit()
        flash('错题添加成功', 'success')
        return redirect(url_for('main.problems'))
    return render_template('main/add-problem.html', subjects=Subject.query.all())


@main.route('/problems/delete/<int:id>/')
@login_required
@student_required
def delete_problem(id):
    problem = Problem.query.get_or_404(id)
    for tag in problem.tags:
        tag.remove_problem(problem)
        if tag.problems.all() == []:
            db.session.delete(tag)
    if problem.body_is_image:
        for img in problem.body.split(','):
            if img != '':
                os.remove(os.path.abspath(os.path.join(current_app.config['UPLOADS_FOLDER'], img)))
    if problem.original_answer_is_image:
        for img in problem.original_answer.split(','):
            if img != '':
                os.remove(os.path.abspath(os.path.join(current_app.config['UPLOADS_FOLDER'], img)))
    if problem.correct_answer_is_image:
        for img in problem.correct_answer.split(','):
            if img !='':
                os.remove(os.path.abspath(os.path.join(current_app.config['UPLOADS_FOLDER'], img)))
    if problem.description_is_image:
        for img in problem.description.split(','):
            if img is not None:
                os.remove(os.path.abspath(os.path.join(current_app.config['UPLOADS_FOLDER'], img)))
    db.session.delete(problem)
    db.session.commit()
    flash('错题已删除', 'success')
    return redirect(url_for('main.problems'))


@main.route('/tags/')
@login_required
@student_required
def tags():
    """查看所有标签"""
    # 获取当前用户的所有标签
    tags = current_user.tags.all()
    return render_template('main/tags.html', tags=tags)


@main.route('/tags/<id>/')
@login_required
@student_required
def tag(id):
    """查看标签"""
    # 获取标签
    tag = current_user.tags.filter_by(id=id).first()
    # 确认标签是否为空
    if tag is None:
        abort(404)
    return render_template('main/tag.html', tag=tag, problems=tag.problems.order_by(Problem.timestamp.desc()).all())


@main.route('/statistics/')
@login_required
@student_required
def statistics():
    """统计错题"""
    # 获取所有标签和错题
    tags = current_user.tags.all()
    problems = current_user.problems.all()
    return render_template('main/statistics.html', tags=tags, problems=problems)


@main.route('/class/add/', methods=['GET', 'POST'])
@login_required
@teacher_required
def add_class():
    """添加班级"""
    if request.method == 'POST':
        name = request.form.get('name')
        join_code = ''.join(str(uuid1()).split('-'))[:4]
        class_ = Class(name=name, join_code=join_code)
        db.session.add(class_)
        db.session.commit()
        class_.join_user(current_user)
        flash('班级添加成功！', 'success')
        return redirect(url_for('main.code_class', name=name))
    subjects = Subject.query.all()
    return render_template('main/add-class.html', subjects=subjects)


@main.route('/class/<name>/code/')
@login_required
@teacher_required
def code_class(name):
    """查看班级码"""
    class_ = Class.query.filter_by(name=name).first()
    if class_ is None:
        abort(404)
    if current_user not in class_.users:
        abort(403)
    return render_template('main/code-class.html', class_=class_)


@main.route('/class/join/', methods=['GET', 'POST'])
@login_required
def join_class():
    """加入班级"""
    if request.method == 'POST':
        name = request.form.get('name')
        code = str(request.form.get('code'))
        class_ = Class.query.filter_by(name=name).first()
        if class_ is None:
            flash('班级不存在', 'error')
            return redirect(url_for('main.join_class'))
        if current_user in class_.users.all():
            flash('您已经了加入此班级', 'warning')
            return redirect(url_for('main.join_class'))
        if code == class_.join_code:
            class_.join_user(current_user)
            flash('加入班级成功', 'success')
            return redirect(url_for('main.index'))
        flash('班级码不正确', 'warning')
        return redirect(url_for('main.join_class'))
    return render_template('main/join-class.html')


@main.route('/class/<name>/')
@login_required
def view_class(name):
    """查看班级"""
    class_ = Class.query.filter_by(name=name).first()
    if class_ is None:
        abort(404)
    if current_user not in class_.users.all():
        abort(403)
    teachers = class_.users.filter_by(
        usertype=UserType.query.filter_by(name='teacher').first()).all()
    students = class_.users.filter_by(
        usertype=UserType.query.filter_by(name='student').first()).all()
    tagall = {}
    problems = 0
    for stu in class_.users.filter_by(usertype=UserType.query.filter_by(name='student').first()).all():
        for tag in stu.tags.all():
            if tag.subject == current_user.subject:
                problems += 1
                name = "%s（%s）" % (tag.name, tag.subject.name)
                try:
                    value = tagall[name] + len(tag.problems.all())
                except KeyError:
                    tagall[name] = len(tag.problems.all())
    return render_template('main/view-class.html', class_=class_, teachers=teachers, students=students, tags=tagall, problems=problems)


@main.route('/class/<name>/manage/')
@login_required
@teacher_required
def manage_class(name):
    """管理班级"""
    class_ = Class.query.filter_by(name=name).first()
    if class_ is None:
        abort(404)
    if current_user not in class_.users.all():
        abort(403)
    teachers = class_.users.filter_by(

app/templates/main/add-class.html
{# 添加班级页面 #}
{% extends 'base.html' %}

{% block title %}添加班级{% endblock %}

{% block content %}
<div class="container">
    <h1>添加班级</h1>
    <hr>
    <form method="post" class="needs-validation" novalidate>
        <div class="form-group">
            <label for="name">名称</label>
            <input class="form-control" name="name" id="name" autocomplete="off" required>
            <div class="invalid-feedback">
                请输入班级名称
            </div>
        </div>
        <button type="submit" class="btn btn-primary">添加班级</button>
    </form>
</div>
{% endblock %}

{% block scripts %}
<script>
    // 表单验证
    (function() {
        window.addEventListener('load', function() {
          // 获取所有页面上需要验证的表单
          var forms = document.getElementsByClassName('needs-validation');
          // 循环遍历并防止它们自动提交
          var validation = Array.prototype.filter.call(forms, function(form) {
            form.addEventListener('submit', function(event) {
              if (form.checkValidity() === false) {
                event.preventDefault();
                event.stopPropagation();
              }
              form.classList.add('was-validated');
            }, false);
          });
        }, false);
      })();
</script>
{% endblock %}

app/templates/main/add-problem.html
{# 添加错题页面 #}
{% extends 'base.html' %}
{% from '_macros.html' import generateTextImageForm %}

{% block title %}添加错题{% endblock %}

{% block content %}
<div class="container">
    <h1>添加错题</h1>
    <hr>
    <form method="post" class="needs-validation" enctype="multipart/form-data" novalidate>
        <div class="form-group">
            <label for="title">标题</label>
            <input id="title" name="title" class="form-control" aria-describedby="titleHelp" autocomplete="off" required>
            <div class="invalid-feedback">
                请输入标题
            </div>
            <small id="titleHelp" class="text-muted">
                该标题将显示在错题列表中，建议选择直观，形象的小标题
            </small>
        </div>
        {{ generateTextImageForm(name='body', text='题目') }}
        {{ generateTextImageForm(name='original-answer', text='原始答案') }}
        {{ generateTextImageForm(name='correct-answer', text='正确答案') }}
        {{ generateTextImageForm(name='description', text='解析') }}
        <div class="form-group">
            <label for="subject">错题科目</label>
            <select class="custom-select" id="subject" autocomplete="off" name="subject">
                {% for subject in subjects %}
                <option value="{{ subject.id }}">{{ subject.name }}</option>
                {% endfor %}
            </select>
            <div class="invalid-feedback">
                请选择科目
            </div>
        </div>
        <div class="form-group">
            <label for="tags">知识点</label>
            <input class="form-control" name="tags" id="tags" autocomplete="off" required>
            <div class="invalid-feedback">
                请输入知识点
            </div>
            <small id="tagsHelp" class="text-muted">
                若有两个或以上知识点请用中文逗号“，”隔开（不包括双引号）
            </small>
        </div>
        <div class="form-group">
            <div class="input-group date" id="datetimePicker" data-target-input="nearest">
                <input type="text" id="inputDate" class="form-control datetimepicker-input" name="date" data-target="#datetimePicker" autocomplete="off" required>
                <div class="input-group-append" data-target="#datetimePicker" data-toggle="datetimepicker">
                    <div class="input-group-text rounded-right"><i class="fa fa-calendar"></i></div>
                </div>
                <div class="invalid-feedback">
                    请输入日期
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">添加错题</button>
    </form>
</div>
{% endblock %}

{% block scripts %}
<script>
    // 表单验证
    (function () {
        window.addEventListener('load', function () {
            // 获取所有页面上需要验证的表单
            var forms = document.getElementsByClassName('needs-validation');
            // 循环遍历并防止它们自动提交
            var validation = Array.prototype.filter.call(forms, function (form) {
                form.addEventListener('submit', function (event) {
                    if (form.checkValidity() === false) {
                        event.preventDefault();
                        event.stopPropagation();
                    }
                    form.classList.add('was-validated');
                }, false);
            });
        }, false);
    })();
</script>
<script type="text/javascript">
    $(function () {
        $('#datetimePicker').datetimepicker({
            locale: 'zh-CN',
            format: 'L'
        });
    });
</script>
{% endblock %}

app/templates/main/change-class-name.html
{# 更改班级名称页面 #}
{% extends 'base.html' %}

{% block title %}更改班级名称{% endblock %}

{% block content %}
<div class="container">
    <h1>更改班级名称</h1>
    <hr>
    <form method="post" class="needs-validation" novalidate>
        <div class="form-group">
            <label for="new-name">新名称</label>
            <input class="form-control" name="new-name" id="new-name" autocomplete="off" value="{{ class_.name }}" required>
            <div class="invalid-feedback">
                请输入新的班级名称
            </div>
        </div>
        <button type="submit" class="btn btn-primary">更改名称</button>
    </form>
</div>
{% endblock %}

{% block scripts %}
<script>
    // 表单验证
    (function() {
        window.addEventListener('load', function() {
          // 获取所有页面上需要验证的表单
          var forms = document.getElementsByClassName('needs-validation');
          // 循环遍历并防止它们自动提交
          var validation = Array.prototype.filter.call(forms, function(form) {
            form.addEventListener('submit', function(event) {
              if (form.checkValidity() === false) {
                event.preventDefault();
                event.stopPropagation();
              }
              form.classList.add('was-validated');
            }, false);
          });
        }, false);
      })();
</script>
{% endblock %}

app/templates/main/code-class.html
{# 查看班级码页面 #}
{% extends 'base.html' %}

{% block title %}查看班级码{% endblock %}

{% block content %}
<div class="container">
    <h1>查看班级码</h1>
    <hr>
    <p>班级“{{ class_.name }}”的班级码为：{{ class_.join_code }}</p>
    <p>将班级码复制给要加入的学生，告诉他们按以下步骤操作：</p>
    <br>
    <div class="row">
        <div class="col col-4">
            <h5>1. 注册账号</h5>
            <p class="text-muted">
                进入<a href="{{ url_for('main.index') }}">智错题首页</a>，点击<code>注册</code>，
                然后让学生按照真实情况填写注册表单
            </p>
        </div>
        <div class="col col-4">
            <h5>2. 加入班级</h5>
            <p class="text-muted">
                在学生注册完账号之后，进入智错题首页，点击学生的姓名 -> 加入班级，将跳转到加入班级页面
            </p>
        </div>
        <div class="col col-4">
            <h5>3. 输入班级码</h5>
            <p class="text-muted">
                在加入班级页面中，先输入班级名称，接着再输入输入本页最上方的班级码，点击<code>加入班级</code>
            </p>
        </div>
    </div>
    <br>
    <p>若要让老师加入班级，操作方法类似，也需要班级码作为验证</p>
</div>
{% endblock %}

app/templates/main/index.html
{# 网站首页 #}
{% extends 'base.html' %}

{% block title %}首页{% endblock %}

{% block content %}
<div class="container">
    <h1 class="text-center display-3">智错题 <small style="font-size: 20px;">- 智慧管理你的错题</small></h1>
    <hr>
    <p class="text-center">智错题是一款线上错题本，用于让错题管理更方便，更快捷。<br>初战未捷，那就努力再努力。</p>
    <br><br>
    <div class="row">
        <div class="col col-4 text-center">
            <h5><span class="text-primary fa fa-pie-chart"></span>&nbsp;&nbsp;&nbsp;强大的数据分析</h5>
            <p class="text-muted">每一个错题的背后，都有着许许多多的知识点，易错点。智错题的任务是分析这些错题，并且以图表的方式呈现给用户，方便复习与整理。</p>
            <img src="{{ url_for('static', filename='images/notebook1.png') }}" class="img-fluid">
        </div>
        <div class="col col-4 text-center">
            <h5><span class="text-primary fa fa-bolt"></span>&nbsp;&nbsp;&nbsp;方便的错题管理</h5>
            <p class="text-muted">将错题存放在智错题，以后就再也不用找不着错题啦！这节省了很多寻找错题本的时间。</p>
            <img src="{{ url_for('static', filename='images/notebook2.png') }}" class="img-fluid">
        </div>
        <div class="col col-4 text-center">
            <h5><span class="text-primary fa fa-users"></span>&nbsp;&nbsp;&nbsp;班级查看功能</h5>
            <p class="text-muted">智错题的班级功能是为老师设计的，目的是让老师更清楚地了解学生哪些知识点较为薄弱，节省课上时间。</p>
            <img src="{{ url_for('static', filename='images/notebook3.png') }}" class="img-fluid">
        </div>
    </div>
</div>
{% endblock %}

app/templates/main/join-class.html
{# 加入班级页面 #}
{% extends 'base.html' %}

{% block title %}加入班级{% endblock %}

{% block content %}
<div class="container">
    <h1>加入班级</h1>
    <hr>
    <form method="post" class="needs-validation" novalidate>
        <div class="form-group">
            <label for="name">名称</label>
            <input class="form-control" name="name" id="name" autocomplete="off" required>
            <div class="invalid-feedback">
                请输入班级名称
            </div>
        </div>
        <div class="form-group">
            <label for="code">班级码</label>
            <input class="form-control" name="code" id="code" autocomplete="off" required>
            <div class="invalid-feedback">
                请输入班级码
            </div>
        </div>
        <button type="submit" class="btn btn-primary">加入班级</button>
    </form>
</div>
{% endblock %}

{% block scripts %}
<script>
    // 表单验证
    (function() {
        window.addEventListener('load', function() {
          // 获取所有页面上需要验证的表单
          var forms = document.getElementsByClassName('needs-validation');
          // 循环遍历并防止它们自动提交
          var validation = Array.prototype.filter.call(forms, function(form) {
            form.addEventListener('submit', function(event) {
              if (form.checkValidity() === false) {
                event.preventDefault();
                event.stopPropagation();
              }
              form.classList.add('was-validated');
            }, false);
          });
        }, false);
      })();
</script>
{% endblock %}

app/templates/main/manage-class.html
{# 管理班级页面 #}
{% extends 'base.html' %}

{% block title %}管理班级{% endblock %}

{% block content %}
<div class="container">
    <h1>管理班级“{{ class_.name }}” <a href="{{ url_for('main.view_class', name=class_.name) }}" style="font-size: 16px;">&laquo; 返回班级</a>&nbsp;&nbsp;<a style="font-size: 16px;" href="{{ url_for('main.change_class_name', name=class_.name) }}"><span class="fa fa-gear"></span> 更改班级名称</a></h1>
    <hr>
    <p class="text-muted">
        本班共有{{ class_.users.all() | length }}人，其中有{{ teachers | length }}名老师和{{ students | length }}名同学。
    </p>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">姓名</th>
                <th scope="col">类别</th>
                <th scope="col">操作</th>
            </tr>
        </thead>
        <tbody>
            {% for user in class_.users.all() %}
            <tr>
                <th scope="row">{{ loop.index }}</th>
                <td>{{ user.name }}</td>
                <td>{% if user.usertype.name == 'teacher' %}老师{% else %}学生{% endif %}</td>
                <td>
                    {% if not user.is_teacher() %}
                    <a class="btn btn-primary" href="{{ url_for('main.view_student_problems', name=class_.name, id=user.id) }}">
                        查看{{ current_user.subject.name }}错题
                    </a>
                    <a class="btn btn-success" href="{{ url_for('main.view_student_statistics', name=class_.name, id=user.id) }}">
                        查看错题统计
                    </a>
                    {% endif %}
                    <button type="button" class="btn btn-danger" data-toggle="modal"
                        data-target="#confirm{{ user.id }}">
                        移除
                    </button>
                </td>
                <div class="modal fade" id="confirm{{ user.id }}" data-backdrop="static" tabindex="-1" role="dialog"
                    aria-labelledby="confirmLabel{{ id }}" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="confirmLabel{{ id }}">确认移除</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                你确认移除成员{{ user.name }}吗？移除后用户仍可以通过加入班级再次加入。
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">取消</button>
                                <a class="btn btn-danger" href="{{ url_for('main.remove_user_from_class', name=class_.name, id=user.id) }}">移除</a>
                            </div>
                        </div>
                    </div>
                </div>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

app/templates/main/problem.html
{# 查看错题页面 #}
{% extends 'base.html' %}

{% block title %}查看错题{% endblock %}

{% block content %}
<div class="container">
    <h1>
        查看错题&nbsp;&nbsp;&nbsp;<small style="font-size: 16px;"><span class="fa fa-book"></span> {{ problem.subject.name }}&nbsp;&nbsp;&nbsp;<span class="fa fa-calendar"></span> {{ moment(problem.timestamp).format('LL') }}</small>
        &nbsp;<small style="font-size: 16px;">
            <a href="{{ url_for('main.problems') }}">
                &laquo; 返回我的错题
            </a>
        </small>
    </h1>
    <hr>
    {% include '_problem.html' %}
</div>
{% endblock %}

app/templates/main/statistics.html
{# 统计页面 #}
{% extends 'base.html' %}

{% block title %}错题统计{% endblock %}

{% block content %}
<div class="container">
    <h1>错题统计</h1>
    <hr>
    {% if tags == [] %}
    <p>还没有任何错题，快去添加一个吧</p>
    {% else %}
    <p>目前有{{ current_user.problems.all() | length }}道错题，继续努力！</p>
    <div id="main" style="width: 80vw;height:50vh;" class="text-center"></div>
    <small class="text-muted">注：若一道题有多个标签，在图表中将算为不同的题进行计算</small>
    {% endif %}
</div>
{% endblock %}

{% block scripts %}
<script>
    var myChart = echarts.init(document.getElementById('main'), 'shine');
    myChart.setOption({
        tooltip: {
            trigger: 'item',
            formatter: '{a} <br/>{b} : {c} ({d}%)'
        },
        series : [
            {
                name: '知识点',
                type: 'pie',
                data:[
                {% for tag in tags %}
                {{ '{value: ' }}{{ tag.problems.all() | length }}, name: '{{ tag.name }}（{{ tag.subject.name }}）'{{ '}' }},
                {% endfor %}
                ],
                animationType: 'scale',
                animationEasing: 'elasticOut',
                animationDelay: function (idx) {
                    return Math.random() * 200;
                }
            }
        ]
    })
    myChart.setOption(option);
</script>
{% endblock %}

app/templates/main/view-class.html
{# 查看班级页面 #}
{% extends 'base.html' %}

{% block title %}{{ class_.name }}{% endblock %}

{% block content %}
<div class="container">
    <h1>
        班级“{{ class_.name }}”
        {% if current_user.is_teacher() %}
        <a href="{{ url_for('main.manage_class', name=class_.name) }}" style="font-size: 16px;"><span class="fa fa-sliders"></span> 管理班级</a>
        <a href="{{ url_for('main.code_class', name=class_.name) }}" style="font-size: 16px;"><span class="fa fa-eye"></span> 查看班级码</a>
        {% endif %}
    </h1>
    <hr>
    <p class="text-muted">本班共有{{ class_.users.all() | length }}人，其中有{{ teachers | length }}名老师和{{ students | length }}名同学。</p>
    {% if current_user.is_teacher() %}
    <p>目前有{{ problems }}个{{ current_user.subject.name }}标签</p>
    <div id="main" style="width: 80vw;height:50vh;" class="text-center"></div>
    <small class="text-muted">注：若一道题有多个标签，在图表中将算为不同的题进行计算</small>
    {% endif %}
</div>
{% endblock %}

{% block scripts %}
<script>
    var myChart = echarts.init(document.getElementById('main'), 'shine');
    myChart.setOption({
        tooltip: {
            trigger: 'item',
            formatter: '{a} <br/>{b} : {c} ({d}%)'
        },
        series : [
            {
                name: '知识点',
                type: 'pie',
                data:[
                {% for tag in tags %}
                {{ '{value: ' }}{{ tags[tag] }}, name: '{{ tag }}'{{ '}' }},
                {% endfor %}
                ],
                animationType: 'scale',
                animationEasing: 'elasticOut',
                animationDelay: function (idx) {
                    return Math.random() * 200;
                }
            }
        ]
    })
    myChart.setOption(option);
</script>
{% endblock %}

app/templates/main/view-student-problem.html
{# 查看错题页面 #}
{% extends 'base.html' %}

{% block title %}查看错题{% endblock %}

{% block content %}
<div class="container">
    <h1>
        查看错题&nbsp;&nbsp;&nbsp;<small style="font-size: 16px;"><span class="fa fa-book"></span> {{ problem.subject.name }}&nbsp;&nbsp;&nbsp;<span class="fa fa-calendar"></span> {{ moment(problem.timestamp).format('LL') }}</small>
        &nbsp;<small style="font-size: 16px;">
            <a href="{{ url_for('main.view_student_problems', name=class_.name, id=user.id) }}">
                &laquo; 返回{{ user.name }}的错题
            </a>
        </small>
    </h1>
    <hr>
    {% include '_teacher-problem.html' %}
</div>
{% endblock %}

app/templates/main/view-student-problems.html
{# 查看班级内指定学生错题的页面 #}
{% extends 'base.html' %}

{% block title %}查看学生错题{% endblock %}

{% block content %}
<div class="container">
    <h1>查看学生“{{ user.name }}”的{{ current_user.subject.name }}错题 <a href="{{ url_for('main.view_student_tags', name=class_.name, id=user.id) }}" style="font-size: 16px;">查看学生的标签</a></h1>
    <hr>
    {% if problems %}
    {% include '_teacher-problems.html' %}
    {% else %}
    <p>TA还没有错题</p>
    {% endif %}
</div>
{% endblock %}

app/templates/main/view-student-tag.html
{# 查看班级内指定学生的指定标签 #}
{% extends 'base.html' %}

{% block title %}{{ user.name }}的标签{% endblock %}

{% block content %}
<div class="container">
    <h1>{{ user.name }}的知识点“{{ tag.name }}”</h1>
    <hr>
    {% include '_teacher-problems.html' %}
</div>
{% endblock %}

app/templates/main/view-student-tags.html
{# 查看班级内指定学生的所有标签 #}
{% extends 'base.html' %}

{% block title %}{{ user.name }}的标签{% endblock %}

{% block content %}
<div class="container">
    <h1>{{ user.name }}的知识点</h1>
    <hr>
    {% for tag in tags %}
    <div class="position-relative">
        <a href="{{ url_for('main.view_student_tag', name=class_.name, id=user.id, tag=tag.id) }}" class="stretched-link">
            <h5>{{ tag.name }}</h5>
        </a>
        <p class="text-muted">
            共{{ tag.problems.all() | length }}道错题
        </p>
        <hr>
    </div>
    {% endfor %}
</div>
{% endblock %}